config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes, only:[:index, :show, :new, :create, :destroy, :update] do 
    resources :recipe_foods, only: [:new,:create,:destroy, :edit, :update]
  end
  resources :foods, only: [:destroy,:index,:new,:create]
  get 'public_recipes', to: 'public_recipes#index'

  root "foods#index"
  get 'shopping_list', to: 'shopping_list#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    return unless user.present?

    can [:create], Recipe
    can %i[read update destroy], Recipe, user_id: user.id
    can :read, Recipe, public: true
    can :manage, RecipeFood

    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_food, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, numericality: { integer_only: true, greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_food, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates :cooking_time, presence: true
  validates :preperation_time, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :recipe_id, presence: true
  validates :food_id, presence: true
  validates :quantity, presence: true
  validates :quantity, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password,
               :current_password)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods
  def index
    @foods = Food.where(user: current_user)
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # POST /foods
  def create
    @food = current_user.foods.build(food_params)

    if @food.save
      redirect_to foods_url, notice: 'Food was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # DELETE /foods/1
  def destroy
    @food = Food.find(params[:id])
    @food.destroy

    if @food.destroy
      flash[:notice] = 'food deleted successfully.'
    else
      flash[:error] = 'Failed to delete food.'
    end
    redirect_to foods_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.where(public: true).includes(:user).order('created_at DESC')
    @ingredients = RecipeFood.all
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: %i[show edit update destroy]
  load_and_authorize_resource

  # GET /recipe_foods/new
  def new
    @recipe_food = RecipeFood.new
    @foods = Food.where(user: current_user)
  end

  # GET /recipe_foods/1/edit
  def edit
    @recipe_food = RecipeFood.find(params[:id])
    @foods = Food.where(user: current_user)
  end

  # POST /recipe_foods or /recipe_foods.json
  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe_id = params[:recipe_id]
    if @recipe_food.save
      redirect_to recipe_path(@recipe_food.recipe_id), notice: 'Ingredient has been added successfully!'
    else
      flash[:alert] = 'Failed creating ingredient'
      redirect_back(fallback_location: root_path)
    end
  end

  # PATCH/PUT /recipe_foods/1 or /recipe_foods/1.json
  def update
    if @recipe_food.update(recipe_food_params)
      redirect_to recipe_url(params[:recipe_id]), notice: 'Recipe food was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /recipe_foods/1 or /recipe_foods/1.json
  def destroy
    @recipe_food.destroy
    redirect_to recipe_url(params[:recipe_id]), notice: 'Ingredient was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :recipe_id, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  load_and_authorize_resource

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.where(user: current_user)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    @ingredients = @recipe.recipe_food.where(recipe: @recipe)
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to recipes_url, notice: 'Recipe was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy
    redirect_to recipes_url, notice: 'Recipe was successfully destroyed.'
  end

  def update
    @recipe.public = !@recipe.public
    @recipe.save
    redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preperation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  def index
    @user = current_user
    @recipe = Recipe.where(user: @user)
    @ingredients = RecipeFood.where(recipe: @recipe).group_by { |ingredient| ingredient.food.name }
    @total_price = @ingredients.map do |_food, ingredients|
      ingredients.map do |ingredient|
        ingredient.quantity * ingredient.food.price
      end.sum
    end.sum
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Measurement unit:</strong>
    <%= food.measurement_unit %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= food.quantity %>
  </p>

  <p>
    <strong>User:</strong>
    <%= food.user_id %>
  </p>

</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<div id="foods" class="food">
  <div class="new_food">
      <%= link_to "Add food", new_food_path %>
  </div>
  <div>
    <table class="food_table">
      <thead>
        <tr>
          <th>Food</th>
          <th>Mesurement unit</th>
          <th>Unit price</th>
          <th>Quantity</th>
          <th>Action</th>
         </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
           <tr>
            <td><%= food.name %></td>
            <td><%= food.measurement_unit %></td>
            <td><%= food.price %>$</td>
            <td><%= food.quantity %></td>
            <td> <%= button_to "Delete",food_path(food), method: :delete, data: { confirm: "Are you sure?" }, class: 'delete-btn' %> </td>
           </tr>
         <% end %>
       </tbody>
    </table>
  </div>
</div>

app/views/foods/new.html.erb
<div class="new-food">
  <h1>New food</h1>

  <%= render "form", food: @food %>

  <br>

  <div>
    <%= link_to "Back to foods", foods_path %>
  </div>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render "shared/navigation" %>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>

app/views/public_recipes/index.html.erb
<div class="row">
<h2 class="text-center">Public Recipes</h2>
<% @recipes.each do |recipe|%>
<div class="container">
<div class="shadow-lg m-3 bg-white public-card">
    <div class="card-body">
      <%= link_to recipe_path(recipe.id), class: 'text-decoration-none d-flex align-items-center justify-content-center' do %>
      <div class="d-flex flex-column w-50 text-center">
        <h5 class="card-title py-3 "><%= recipe.name.capitalize %></h3>
        <p class="mb-0 py-3">By: <%= recipe.user.name.capitalize %></p>
      </div>
          <div class="d-flex w-50 flex-column text-center">
            <p class="py-3 mb-0">Total food items: <%= @ingredients.where(recipe: recipe).count %></p>
            <p class="py-3 mb-0">Total Price: $ <%= @ingredients.where(recipe: recipe).map {|value| value.food.price * value.quantity}.sum %></p>
          </div>
      <% end %>
    </div>
</div>
</div>
<% end %>
</div>

app/views/recipe_foods/edit.html.erb
<div class="container">
  <h1>Edit Ingredient</h1>
  <%= form_with model: @recipe_food, url: recipe_recipe_food_path(recipe_id: @recipe_food.recipe_id, id: @recipe_food.id), method: :patch do |f| %>
    <%= f.hidden_field :id, value: @recipe_food.id %>
    <%= f.hidden_field :recipe_id, value: @recipe_food.recipe_id %>
    <br>
    <p>Select Ingredient</p>
    <%= f.select :food_id, @foods.map { |food| [food.name, food.id] }, {}, { class:'form-select'} %>

    <br>
    <p>Quantity</p>
    <%= f.number_field :quantity, { class:'form-select'} %>
    <%= f.submit "Add Ingredient" %>
  <% end %>
</div>

app/views/recipe_foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipe foods</h1>

<div id="recipe_foods">
  <% @recipe_foods.each do |recipe_food| %>
    <%= render recipe_food %>
    <p>
      <%= link_to "Show this recipe food", recipe_food %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe food", new_recipe_food_path %>

app/views/recipe_foods/new.html.erb
<div class="container">
  <h1>Add Ingredient</h1>
  <%= form_with model: @recipe_food, url: recipe_recipe_foods_path do |form| %>

    <br>
    <p>Select Ingredient</p>
    <br>

    <p>Food name</p>
    <%= form.select :food_id, @foods.map { |food| [food.name, food.id] }, {}, { class:'form-select'} %>
    <br>
    <p>Quantity</p>
    <%= form.number_field :quantity, class:'form-control' %>
    <br>
    <%= form.submit "Add Ingredient" %>
  <% end %>
</div>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preperation_time, style: "display: block" %>
    <%= form.text_field :preperation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.text_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/index.html.erb
<div class="container-fluid container">
  <% if @recipes.empty? %>

  <div class="text-decoration-none mb-5 mx-auto d-flex justify-content-center">
      <h2 class="text-center me-6">No recipes available</h2>
      <%= link_to "Add new recipe", new_recipe_path, class: 'btn btn-secondary text text-centet' %>
  </div>

  <% else %>

    <h3 class="text-center">My Recipes</h3>
    <div class="text-end mb-3">
      <%= link_to "Add new recipe", new_recipe_path, class: 'btn btn-secondary' %>
    </div>

    <% @recipes.each do |recipe| %>
      <div class="container-fluid mb-4 border border-">
      <%= link_to recipe_path(recipe.id), class: 'text-decoration-none' do%>
        <div class="row border border-1 align-items-center">
            <div class="col-sm-3 p-3">
              <h4><%= recipe.name %></h4>
          </div>
          <div class="col col-sm-9 overflow-hidden">
            <p class="card-text"><%= recipe.description %></p>
          </div>
        </div>
        <%end%>
         <div class="mb-2 " >
                    <%= button_to "Remove", recipe_path(recipe.id), class: 'btn btn-danger mt-2', method: :delete %>
         </div>
      </div>
    <% end %>

  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="new-recipe">
  <h1>New recipe</h1>

  <%= render "form", recipe: @recipe %>

  <br>

  <div>
    <%= link_to "Back to recipes", recipes_path %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="d-flex justify-content-between text-decoration-none mb-5 container">
  <div>
    <h3>Name:<%= @recipe.name %> </h3>
    <p>Preparation Time: <%= @recipe.preperation_time%> </p>
    <p>Cooking Time:<%= @recipe.cooking_time %> </p>
    <p>Description:<%= @recipe.description %> </p> 
  </div>
  <div>
   <% if can? :update, @recipe%>
    <% if @recipe.public %>
      <p>Current Status: Public</p>
      <%= button_to "Change public to private", recipe_path(@recipe), method: :patch%>
    <% else %>
      <p>Current Status: Private</p>
      <%= button_to "Change Private to public", recipe_path(@recipe), method: :patch%>
    <% end %>
   <% end %>
  </div>
</div>

<div class="d-flex justify-content-between text-decoration-none mb-5 container">
  <% if can? :update, @recipe%>
    <%= link_to "Generate shopping list",shopping_list_path, class: 'btn btn-secondary' %>
    <%= link_to "Add Ingredient", new_recipe_recipe_food_path(@recipe.id), class: 'btn btn-secondary' %>
  <%end%>
</div>

<table class="table table-striped container">
  <thead>
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Value</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
    <tbody>
    <% @ingredients.each do |ingredient|%>
      <tr>
          <td><%= ingredient.food.name %></td>
          <td><%= ingredient.quantity%> <%= ingredient.food.measurement_unit %></td>
          <td>$ <%= ingredient.food.price %></td>
          <td class="d-flex gap-2 justify-content-center">
          <% if can? :update, @recipe%>
            <%= link_to "Modify", edit_recipe_recipe_food_path(recipe_id: @recipe.id, id: ingredient.id), class: 'modify-btn' %>
            <%= button_to "Remove", recipe_recipe_food_path(recipe_id: @recipe.id, id: ingredient.id), method: :delete, class: 'delete-btn'%>
          <%else%>
            <p>Actions Not allowed</p>
          <%end%>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Recipe App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
      <div class="navbar-nav">
      <% if user_signed_in?%>
         <%= link_to "Foods", foods_path, class: "nav-item nav-link"%>
         <%= link_to "Recipes" , recipes_path, class: "nav-item nav-link" %>
         <%= link_to "Public Recipies", '/public_recipes', class: "nav-item nav-link" %>
         <%= link_to "Shopping list", '/shopping_list', class: "nav-item nav-link" %>
    <%end%>
      </div>
      <div class="d-flex justify-content-end">
      <%if user_signed_in?%>
        <p class="nav-item nav-link">Welcome <%= current_user.name.capitalize %>!</p>
        <%= button_to "Log Out" , destroy_user_session_path, method: :delete, class: "btn btn-outline-secondary nav-item nav-link" %>
    <%end%>
    <div class="d-flex justify-content-center">
      <%unless user_signed_in?%>
        <%= link_to "Sign In" , new_user_session_path, class: "btn btn-outline-secondary nav-item nav-link" %>
        <%= link_to "Sign Up" , new_user_registration_path, class: "btn btn-outline-secondary nav-item nav-link" %>
      <%end%>
      </div>
      </div>
    </div>
  </div>
</nav>

app/views/shopping_list/index.html.erb
<div class="shopping_list">
  <h1>Shopping List</h1>
  <div class="shopping_header">
    <p>Amount of food items to buy: <%= @ingredients.length %></p>
    <p>Total value of food needed: $<%= @total_price %></p>
  </div>

  <table class="food_table">
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% @ingredients.each do |food, ingredients| %>
        <tr>
          <td><%= food %></td>
          <td>
            <% if ingredients.length == 1 %>
              <span><%= ingredients.first.quantity %> <%= ingredients.first.food.measurement_unit %></span>
            <% else %>
              <% total_quantity = ingredients.map(&:quantity).sum %>
              <span><%= total_quantity %> <%= ingredients.first.food.measurement_unit %></span>
            <% end %>
          </td>
          <td>
            <% if ingredients.length == 1 %>
              $<%= ingredients.first.food.price * ingredients.first.quantity %>
            <% else %>
              <% total_price = ingredients.map { |ingredient| ingredient.quantity * ingredient.food.price }.sum %>
              $<%= total_price %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>